name: cmake

on: [push]

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install cmake-format
        run: pip install cmake-format

      - name: Run cmake-format
        run: |
          cmake-format -i ./CMakeLists.txt
          cmake-format -i ./src/CMakeLists.txt
          cmake-format -i ./src/internal/CMakeLists.txt
          cmake-format -i ./tests/CMakeLists.txt
          cmake-format -i ./data/CMakeLists.txt
          cmake-format -i ./cmake/CompilerWarnings.cmake
          cmake-format -i ./cmake/Sanitizers.cmake
          cmake-format -i ./cmake/StaticAnalyzers.cmake

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          signoff: true
          message: 'Format cmake files'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
