name: cmake

on: [push]

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    container: cheshirekow/cmake-format
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Run cmake-format
        run: cmake-format -i ./**/CMakeLists.txt