name: w10

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.15.2]
        platform: [windows-latest]
        arch: [x64]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Installing Qt
        uses: jurplel/install-qt-action@v3.1.0
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build GUI
        shell: pwsh
        run: |
          mkdir build-gui
          cd build-gui
          cmake ..
          cmake --build . --parallel
          ctest --output-on-failure

      - name: Build CLI
        shell: pwsh
        run: |
          mkdir build-cli
          cd build-cli
          cmake -DBUILD_CLI:BOOL=ON ..
          cmake --build . --parallel
          ctest --output-on-failure
